app:
  stock-market:
    markets:
      BSE,
      NSE,
      NYSE,
      ASX
  integration:
    external:
      api:
        yahoo: 'https://apidojo-yahoo-finance-v1.p.rapidapi.com/stock/v2/get-historical-data'
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
spring:
  main:
    banner-mode: off